# Home Manager module: declarative Pywalfox native messaging host.
#
# Usage in your home.nix (or flake home-manager module list):
#
#   imports = [ ./pywalfox.nix ];
#
#   programs.pywalfox = {
#     enable = true;
#     browsers = [ "firefox" "librewolf" ];   # default
#   };
#
# This only handles the native messaging host (the daemon that reads your
# Pywal colors). You still need to install the browser extension itself —
# either manually from https://addons.mozilla.org/firefox/addon/pywalfox/,
# or declaratively via your firefox/librewolf profile's extensions.packages
# if `nur.repos.rycee.firefox-addons.pywalfox` exists in your NUR set.

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.pywalfox;

  # Native messaging manifests must point at an executable invoked with no
  # custom arguments, so we wrap the daemon's "start" subcommand ourselves.
  # This also sidesteps the upstream installer trying (and failing) to
  # chmod +x a file inside the read-only /nix/store.
  pywalfoxStart = pkgs.writeShellScript "pywalfox-start" ''
    exec ${cfg.package}/bin/pywalfox start
  '';

  pywalfoxManifest = pkgs.writeText "pywalfox.json" (builtins.toJSON {
    name = "pywalfox";
    description = "Automatically theme your browser using the colors generated by Pywal";
    path = "${pywalfoxStart}";
    type = "stdio";
    allowed_extensions = [ "pywalfox@frewacom.org" ];
  });

  # Relative (to $HOME) native-messaging-hosts directories to populate,
  # deduplicated across browser choices. LibreWolf currently reads from a
  # separate path than stock Firefox (nix-community/home-manager#6635), so
  # when it's selected we cover both locations to be safe.
  browserDirs = {
    firefox    = [ ".mozilla/native-messaging-hosts" ];
    librewolf  = [ ".librewolf/native-messaging-hosts" ".mozilla/native-messaging-hosts" ];
    thunderbird = [ ".thunderbird/native-messaging-hosts" ];
  };

  dirs = unique (concatMap (b: browserDirs.${b}) cfg.browsers);

  manifestFiles = listToAttrs (map (dir: {
    name = "${dir}/pywalfox.json";
    value = { source = pywalfoxManifest; };
  }) dirs);
in
{
  options.programs.pywalfox = {
    enable = mkEnableOption "Pywalfox native messaging host (Pywal theming for Firefox-based browsers)";

    package = mkOption {
      type = types.package;
      default = pkgs.pywalfox-native;
      defaultText = literalExpression "pkgs.pywalfox-native";
      description = "The pywalfox-native package providing the `pywalfox` daemon.";
    };

    browsers = mkOption {
      type = types.listOf (types.enum [ "firefox" "librewolf" "thunderbird" ]);
      default = [ "firefox" "librewolf" ];
      description = "Which browsers to install the native messaging manifest for.";
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];
    home.file = manifestFiles;
  };
}
